import { Link, useParams } from 'react-router'

import { useTickerData } from '@/lib/loadTickerData'
import { RecommendationBanner } from '@/components/RecommendationBanner'
import { DriversList } from '@/components/DriversList'
import { DissentPanel } from '@/components/DissentPanel'
import { CurrentPriceDelta } from '@/components/CurrentPriceDelta'
import { EndorsementsList } from '@/components/EndorsementsList'
import { Separator } from '@/components/ui/separator'
import { FetchNotFoundError, SchemaMismatchError } from '@/lib/fetchSnapshot'

// DecisionRoute — Decision-Support View at /decision/:symbol/:date?.
//
// Pattern adapted from TickerRoute.tsx — same loading/typed-error branches,
// different content focus (recommendation-first, not analysis-first). The
// deep-dive (TickerRoute) answers "what's the data"; this route answers
// "what should I do" — banner-as-hero, drivers as supporting evidence,
// dissent panel ALWAYS rendered (Pitfall #12 confirmation-bias guard).
//
// Composition order (top-down):
//   1. Heading + ← Deep dive cross-link (date preserved on round-trip)
//   2. data_unavailable notice (only when dec.data_unavailable === true)
//   3. RecommendationBanner — hero
//   4. CurrentPriceDelta — Phase 8 Wave 1 (replaced the Phase-7 placeholder).
//      data-testid='current-price-placeholder' preserved for grep continuity.
//   5. DriversList — short_term + long_term card pair
//   6. Separator
//   7. DissentPanel — always rendered
//   8. open_observation block (only when truthy) — accent-tinted
//
// Lite-mode handling: when ticker_decision === null (lite-mode synthesizer
// skip), render an explicit amber "No recommendation" notice — mirrors
// TickerRoute null-decision handling so the user sees an intentional
// "we didn't synthesize today" state, not a blank page.

function isFetchNotFound(err: unknown): err is FetchNotFoundError {
  return err instanceof FetchNotFoundError
}

function isSchemaMismatch(err: unknown): err is SchemaMismatchError {
  return err instanceof SchemaMismatchError
}

export default function DecisionRoute() {
  const { symbol = '', date = 'today' } = useParams<{
    symbol: string
    date?: string
  }>()
  const { data: snap, isLoading, error } = useTickerData(date, symbol)

  if (isLoading) {
    return (
      <section>
        <h1 className="font-mono text-3xl font-semibold tracking-tight">
          {symbol}
        </h1>
        <div
          className="mt-12 text-sm text-fg-muted"
          data-testid="decision-loading"
        >
          Loading {symbol}…
        </div>
      </section>
    )
  }

  if (error) {
    let title = `Failed to load ${symbol}`
    let detail = (error as Error).message
    if (isFetchNotFound(error)) {
      title = `${symbol} not in snapshot for ${date}`
      detail =
        'The selected ticker has no data for this date. It may have failed during the routine — see the scan view.'
    } else if (isSchemaMismatch(error)) {
      title = 'Schema upgrade required'
      detail =
        "The snapshot was generated by an older routine. Re-run today's routine or upgrade the frontend."
    }
    return (
      <section className="space-y-6">
        <div className="flex items-baseline justify-between gap-4">
          <h1 className="font-mono text-3xl font-semibold tracking-tight">
            {symbol}
          </h1>
          <Link
            to={`/scan/${date}`}
            className="text-sm text-fg-muted hover:text-accent"
          >
            ← Back to scan
          </Link>
        </div>
        <div
          className="rounded-md border border-bearish/30 bg-bearish/10 px-4 py-3 text-sm text-bearish"
          data-testid="decision-error"
        >
          <strong className="font-mono">{title}</strong>
          <div className="mt-1 text-fg-muted">{detail}</div>
        </div>
      </section>
    )
  }

  if (!snap) return null

  const dec = snap.ticker_decision

  // Lite-mode null-decision branch — explicit amber notice mirrors
  // TickerRoute's posture for the "no synthesis today" case.
  if (dec === null) {
    return (
      <section className="flex flex-col gap-6 pb-12" data-testid="decision-route">
        <div className="flex flex-wrap items-baseline justify-between gap-4">
          <h1
            className="font-mono text-3xl font-semibold tracking-tight"
            data-testid="decision-heading"
          >
            {snap.ticker}
          </h1>
          <Link
            to={`/ticker/${symbol}/${date}`}
            className="text-sm text-fg-muted hover:text-accent"
            data-testid="back-to-deep-dive-link"
          >
            ← Deep dive
          </Link>
        </div>
        <div
          className="rounded-md border border-amber/30 bg-amber/10 px-4 py-3 text-sm text-amber"
          data-testid="decision-no-recommendation"
        >
          <strong className="font-mono">No recommendation for {symbol} on {date}</strong>
          <div className="mt-1 text-fg-muted">
            ticker_decision is null — likely lite-mode run. Re-run today's
            routine to populate the recommendation.
          </div>
        </div>
      </section>
    )
  }

  return (
    <section className="flex flex-col gap-8 pb-12" data-testid="decision-route">
      {/* 1. Heading + Phase 7 cross-link back to TickerRoute */}
      <div className="flex flex-wrap items-baseline justify-between gap-4">
        <h1
          className="font-mono text-3xl font-semibold tracking-tight"
          data-testid="decision-heading"
        >
          {snap.ticker}
        </h1>
        <Link
          to={`/ticker/${symbol}/${date}`}
          className="text-sm text-fg-muted hover:text-accent"
          data-testid="back-to-deep-dive-link"
        >
          ← Deep dive
        </Link>
      </div>

      {/* 2. data_unavailable notice — appears ABOVE the banner so the user
          reads "partial data" before the recommendation. Phase 5 schema
          invariant: data_unavailable=true ⟹ recommendation='hold' AND
          conviction='low' (zod refine). */}
      {dec.data_unavailable && (
        <div
          className="rounded-md border border-fg-muted/30 bg-surface px-4 py-3 text-sm text-fg-muted"
          data-testid="data-unavailable-notice"
        >
          ⚠ Data unavailable for some signals — recommendation may be partial
        </div>
      )}

      {/* 3. RecommendationBanner — hero */}
      <RecommendationBanner
        recommendation={dec.recommendation}
        conviction={dec.conviction}
      />

      {/* 4. CurrentPriceDelta — Phase 8 Wave 1 close. Replaces the Phase-7
          placeholder. data-testid='current-price-placeholder' is preserved
          on the new element for grep-target continuity. snapshotLastPrice
          derives from the latest ohlc_history close (final bar in the v2
          snapshot's price series). */}
      <CurrentPriceDelta
        symbol={symbol}
        snapshotLastPrice={
          snap.ohlc_history.length > 0
            ? snap.ohlc_history[snap.ohlc_history.length - 1].close
            : null
        }
        snapshotComputedAt={dec.computed_at}
      />

      {/* 5. DriversList — short_term + long_term card pair */}
      <DriversList shortTerm={dec.short_term} longTerm={dec.long_term} />

      <Separator />

      {/* 7. DissentPanel — ALWAYS rendered (Pitfall #12 lock) */}
      <DissentPanel dissent={dec.dissent} />

      {/* 7b. EndorsementsList — Phase 9 / ENDORSE-03 mount lock. Renders
          immediately AFTER DissentPanel, BEFORE the open_observation block.
          Last 90 days for active ticker; date-desc; NO performance number
          (deferred to v1.x ENDORSE-04..06). */}
      <EndorsementsList symbol={symbol} />

      {/* 8. open_observation — accent-tinted (matches DissentPanel claude
          case + OpenClaudePin from Phase 6) when present. */}
      {dec.open_observation && (
        <div
          className="rounded-md border border-accent/40 bg-accent/5 px-6 py-4 text-fg"
          data-testid="open-observation"
        >
          <span className="font-mono text-xs uppercase tracking-wider text-accent">
            Open Claude Observation
          </span>
          <p className="mt-2 text-sm leading-relaxed">{dec.open_observation}</p>
        </div>
      )}
    </section>
  )
}
