import { useParams } from 'react-router'
import { useScanData } from '@/lib/loadScanData'
import { LensTabs } from '@/components/LensTabs'
import { PositionLens } from '@/components/lenses/PositionLens'
import { ShortTermLens } from '@/components/lenses/ShortTermLens'
import { LongTermLens } from '@/components/lenses/LongTermLens'
import { FetchNotFoundError, SchemaMismatchError } from '@/lib/fetchSnapshot'

// ScanRoute — Wave 2 implementation. Replaces the Wave 1 stub.
//
// Layout:
//   - heading "Morning Scan — {date}"
//   - partial-data banner (only if status.partial OR failedTickers.length > 0)
//   - LensTabs with the 3 lens components (one visible at a time)
//
// Loading state: muted "Loading scan…" placeholder.
// Error state:
//   - SchemaMismatchError → explicit "schema upgrade required" banner
//     (CONTEXT.md UNIFORM RULE)
//   - FetchNotFoundError → "snapshot not found for this date"
//   - other Error → generic failure with message

function isFetchNotFound(err: unknown): err is FetchNotFoundError {
  return err instanceof FetchNotFoundError
}

function isSchemaMismatch(err: unknown): err is SchemaMismatchError {
  return err instanceof SchemaMismatchError
}

export default function ScanRoute() {
  const { date = 'today' } = useParams<{ date: string }>()
  const { data, isLoading, error } = useScanData(date)

  if (isLoading) {
    return (
      <section>
        <h1 className="text-2xl font-semibold tracking-tight">
          Morning Scan — {date}
        </h1>
        <div
          className="mt-12 text-sm text-fg-muted"
          data-testid="scan-loading"
        >
          Loading scan…
        </div>
      </section>
    )
  }

  if (error) {
    let title = 'Failed to load scan'
    let detail = (error as Error).message
    if (isFetchNotFound(error)) {
      title = `No snapshot for ${date}`
      detail = 'The selected date has no scan data. Try a different date.'
    } else if (isSchemaMismatch(error)) {
      title = 'Schema upgrade required'
      detail =
        'The snapshot was generated by an older routine. Re-run today\'s routine or upgrade the frontend.'
    }
    return (
      <section>
        <h1 className="text-2xl font-semibold tracking-tight">
          Morning Scan — {date}
        </h1>
        <div
          className="mt-6 rounded-md border border-bearish/30 bg-bearish/10 px-4 py-3 text-sm text-bearish"
          data-testid="scan-error"
        >
          <strong className="font-mono">{title}</strong>
          <div className="mt-1 text-fg-muted">{detail}</div>
        </div>
      </section>
    )
  }

  if (!data) return null

  const totalTickers = data.index.tickers.length
  const loadedTickers = Object.keys(data.snapshots).length
  const partial = data.status.partial || data.failedTickers.length > 0

  return (
    <section className="flex flex-col gap-6">
      <div className="flex flex-wrap items-baseline justify-between gap-4">
        <h1 className="text-2xl font-semibold tracking-tight">
          Morning Scan — {date}
        </h1>
        <span className="font-mono text-xs text-fg-muted">
          {loadedTickers}/{totalTickers} tickers
          {data.index.lite_mode ? ' · lite' : ''}
        </span>
      </div>

      {partial && (
        <div
          className="rounded-md border border-amber/30 bg-amber/10 px-4 py-3 text-sm text-amber"
          data-testid="partial-banner"
        >
          Partial data — {loadedTickers}/{totalTickers} tickers loaded
          {data.failedTickers.length > 0 &&
            ` (${data.failedTickers.length} failed: ${data.failedTickers
              .slice(0, 5)
              .join(', ')}${data.failedTickers.length > 5 ? '…' : ''})`}
        </div>
      )}

      <LensTabs
        positionContent={
          <PositionLens date={date} snapshots={data.snapshots} />
        }
        shortContent={
          <ShortTermLens date={date} snapshots={data.snapshots} />
        }
        longContent={<LongTermLens date={date} snapshots={data.snapshots} />}
      />
    </section>
  )
}
