import { Link, useParams } from 'react-router'

import { useTickerData } from '@/lib/loadTickerData'
import { OpenClaudePin } from '@/components/OpenClaudePin'
import { TimeframeCard } from '@/components/TimeframeCard'
import { Chart } from '@/components/Chart'
import { PersonaCard } from '@/components/PersonaCard'
import { AnalyticalSignalCard } from '@/components/AnalyticalSignalCard'
import { NewsList } from '@/components/NewsList'
import { CurrentPriceDelta } from '@/components/CurrentPriceDelta'
import { Separator } from '@/components/ui/separator'
import { FetchNotFoundError, SchemaMismatchError } from '@/lib/fetchSnapshot'

// TickerRoute — Per-Ticker Deep-Dive view at /ticker/:symbol/:date?.
//
// Layout (top-down per user MEMORY.md "Claude's reasoning surfaced alongside
// personas, never replaced"):
//   1. Heading: ticker symbol + back-to-scan link
//   2. OpenClaudePin (claude_analyst signal — pinned, distinct, ALWAYS rendered)
//   2b. CurrentPriceDelta — Phase 8 Wave 1 mount. Refresh hook dedupes by
//       queryKey ['refresh', symbol] across TickerRoute + DecisionRoute.
//   3. TimeframeCards (short_term + long_term, side-by-side on lg)
//   4. Chart (OHLC + MA20/MA50/BB upper/lower + RSI sub-pane)
//   5. PersonaCards grid (5 personas EXCLUDING claude_analyst)
//   6. AnalyticalSignalCards row (4 signals: fundamentals/technicals/news_sentiment/valuation)
//   7. NewsList (grouped by source, sorted by published_at DESC, NEW tag for
//      headlines newer than snapshot.computed_at)
//
// VIEW-09 LOCK: claude_analyst is rendered SEPARATELY at TOP, NOT in the
// PersonaCards grid. The grid filters out claude_analyst:
//   persona_signals.filter(p => p.analyst_id !== 'claude_analyst')
// → exactly 5 cards (buffett/munger/wood/burry/lynch) when the snapshot has
// the canonical 6 persona_signals. OpenClaudePin always renders, even when
// claude_analyst signal is missing from the array (signal=undefined → muted
// "data unavailable" body — never silently absent).

function isFetchNotFound(err: unknown): err is FetchNotFoundError {
  return err instanceof FetchNotFoundError
}

function isSchemaMismatch(err: unknown): err is SchemaMismatchError {
  return err instanceof SchemaMismatchError
}

export default function TickerRoute() {
  const { symbol = '', date = 'today' } = useParams<{
    symbol: string
    date?: string
  }>()
  const { data: snap, isLoading, error } = useTickerData(date, symbol)

  if (isLoading) {
    return (
      <section>
        <h1 className="font-mono text-3xl font-semibold tracking-tight">
          {symbol}
        </h1>
        <div
          className="mt-12 text-sm text-fg-muted"
          data-testid="ticker-loading"
        >
          Loading {symbol}…
        </div>
      </section>
    )
  }

  if (error) {
    let title = `Failed to load ${symbol}`
    let detail = (error as Error).message
    if (isFetchNotFound(error)) {
      title = `${symbol} not in snapshot for ${date}`
      detail =
        'The selected ticker has no data for this date. It may have failed during the routine — see the scan view.'
    } else if (isSchemaMismatch(error)) {
      title = 'Schema upgrade required'
      detail =
        "The snapshot was generated by an older routine. Re-run today's routine or upgrade the frontend."
    }
    return (
      <section className="space-y-6">
        <div className="flex items-baseline justify-between gap-4">
          <h1 className="font-mono text-3xl font-semibold tracking-tight">
            {symbol}
          </h1>
          <Link
            to={`/scan/${date}`}
            className="text-sm text-fg-muted hover:text-accent"
          >
            ← Back to scan
          </Link>
        </div>
        <div
          className="rounded-md border border-bearish/30 bg-bearish/10 px-4 py-3 text-sm text-bearish"
          data-testid="ticker-error"
        >
          <strong className="font-mono">{title}</strong>
          <div className="mt-1 text-fg-muted">{detail}</div>
        </div>
      </section>
    )
  }

  if (!snap) return null

  const claudeSig = snap.persona_signals.find(
    (p) => p.analyst_id === 'claude_analyst',
  )
  const otherPersonas = snap.persona_signals.filter(
    (p) => p.analyst_id !== 'claude_analyst',
  )
  const dec = snap.ticker_decision
  // snapshotComputedAt: prefer ticker_decision.computed_at; fall back to
  // position_signal.computed_at; final fallback epoch-zero so NewsList NEW
  // tags only fire for definitely-post-snapshot headlines.
  const snapshotComputedAt =
    dec?.computed_at ??
    snap.position_signal?.computed_at ??
    new Date(0).toISOString()

  return (
    <section className="flex flex-col gap-8 pb-12" data-testid="ticker-route">
      {/* 1. Heading + Phase 7 cross-link to /decision/:symbol/:date — preserves date */}
      <div className="flex flex-wrap items-baseline justify-between gap-4">
        <h1
          className="font-mono text-3xl font-semibold tracking-tight"
          data-testid="ticker-heading"
        >
          {snap.ticker}
        </h1>
        <div className="flex items-center gap-4">
          <Link
            to={`/decision/${symbol}/${date}`}
            className="text-sm text-fg-muted hover:text-accent"
            data-testid="to-decision-link"
          >
            → Decision view
          </Link>
          <Link
            to={`/scan/${date}`}
            className="text-sm text-fg-muted hover:text-accent"
            data-testid="back-to-scan-link"
          >
            ← Back to scan
          </Link>
        </div>
      </div>

      {/* 2. Open Claude Analyst pinned at TOP — VIEW-09 + MEMORY.md lock */}
      <OpenClaudePin signal={claudeSig} />

      {/* 2b. Current price + delta — Phase 8 Wave 1. snapshotLastPrice from
          the final ohlc bar's close (snapshot baseline). Hook is shared with
          DecisionRoute via queryKey ['refresh', symbol]. */}
      <CurrentPriceDelta
        symbol={symbol}
        snapshotLastPrice={
          snap.ohlc_history.length > 0
            ? snap.ohlc_history[snap.ohlc_history.length - 1].close
            : null
        }
        snapshotComputedAt={snapshotComputedAt}
      />

      {/* 3. Dual-timeframe cards — VIEW-05 (side-by-side on lg, stacked on mobile) */}
      {dec && (
        <div className="flex flex-col gap-6 lg:flex-row" data-testid="timeframe-cards">
          <TimeframeCard label="Short-Term (1w-1m)" band={dec.short_term} />
          <TimeframeCard label="Long-Term (1y-5y)" band={dec.long_term} />
        </div>
      )}

      {/* 4. OHLC chart with overlays — VIEW-06 */}
      <section>
        <h2 className="mb-3 font-mono text-xs uppercase tracking-wider text-fg-muted">
          Price Chart
        </h2>
        <Chart ohlcHistory={snap.ohlc_history} indicators={snap.indicators} />
      </section>

      <Separator />

      {/* 5. Persona cards grid — VIEW-07 (claude_analyst excluded; pinned above) */}
      {otherPersonas.length > 0 && (
        <section>
          <h2 className="mb-4 font-mono text-xs uppercase tracking-wider text-fg-muted">
            Persona Signals
          </h2>
          <div
            className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-3"
            data-testid="persona-cards-grid"
          >
            {otherPersonas.map((p) => (
              <PersonaCard key={p.analyst_id} signal={p} />
            ))}
          </div>
        </section>
      )}

      {/* 6. Analytical signal cards row */}
      {snap.analytical_signals.length > 0 && (
        <section>
          <h2 className="mb-4 font-mono text-xs uppercase tracking-wider text-fg-muted">
            Analytical Signals
          </h2>
          <div
            className="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-4"
            data-testid="analytical-signals-grid"
          >
            {snap.analytical_signals.map((s) => (
              <AnalyticalSignalCard key={s.analyst_id} signal={s} />
            ))}
          </div>
        </section>
      )}

      <Separator />

      {/* 7. News feed grouped by source — VIEW-08 */}
      <section>
        <h2 className="mb-4 font-mono text-xs uppercase tracking-wider text-fg-muted">
          News Feed
        </h2>
        <NewsList
          headlines={snap.headlines}
          snapshotComputedAt={snapshotComputedAt}
        />
      </section>
    </section>
  )
}
